import subprocess
from datetime import date, datetime, timedelta
from pathlib import Path
import json
import sys

PROGRESS_FILE = Path("daily-progress.txt")
DATA_FILE = Path("daily-progress.json")


def run_command(command):
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()

    except FileNotFoundError:
        print(f"\n❌ Command not found: {command[0]}")
        return None

    except subprocess.CalledProcessError as error:
        print(f"\n❌ Git command failed: {' '.join(command)}")

        if error.stderr:
            print(error.stderr.strip())

        return None


def load_data():
    if not DATA_FILE.exists():
        return {"entries": []}

    try:
        with DATA_FILE.open("r", encoding="utf-8") as file:
            data = json.load(file)

        if isinstance(data, dict) and isinstance(data.get("entries"), list):
            return data

        return {"entries": []}

    except (json.JSONDecodeError, OSError):
        print("⚠️ Could not read daily-progress.json.")
        return {"entries": []}


def save_data(data):
    with DATA_FILE.open("w", encoding="utf-8") as file:
        json.dump(data, file, indent=2, ensure_ascii=False)


def get_entry(data, day):
    for entry in data["entries"]:
        if entry.get("date") == day:
            return entry

    return None


def rebuild_text_file(data):
    lines = [
        "# Developer Daily Progress",
        "# Generated by Dev Daily Tracker",
        ""
    ]

    for entry in data["entries"]:

        lines.append(entry["date"])
        lines.append(
            f"Category: {entry.get('category', 'Other')}"
        )
        lines.append(
            f"Hours: {entry.get('hours', 0)}"
        )

        for item in entry.get("items", []):
            lines.append(f"- {item}")

        lines.append("")

    PROGRESS_FILE.write_text(
        "\n".join(lines),
        encoding="utf-8"
    )


def add_or_update_entry():

    data = load_data()

    today = date.today().isoformat()

    print("\n========================================")
    print("        ADD TODAY'S PROGRESS")
    print("========================================")

    print("Enter one task per line.")
    print("Type DONE when finished.\n")

    items = []

    while True:

        item = input("> ").strip()

        if item.upper() == "DONE":
            break

        if item:
            items.append(item)

    if not items:

        print("\n⚠️ No progress entered.")
        return False

    while True:

        try:

            hours = float(
                input("\nHours worked today (e.g. 2.5): ")
                .strip()
            )

            if hours < 0:
                raise ValueError

            break

        except ValueError:

            print(
                "Please enter a valid positive number."
            )

    categories = {
        "1": "JavaScript",
        "2": "React",
        "3": "Backend",
        "4": "Git/GitHub",
        "5": "Python",
        "6": "HTML/CSS",
        "7": "Other"
    }

    print("\nCategory:")

    for key, value in categories.items():
        print(f"{key}. {value}")

    while True:

        category_choice = input("Choose: ").strip()

        if category_choice in categories:

            category = categories[category_choice]

            break

        print(
            "Please choose a number from 1 to 7."
        )

    existing = get_entry(data, today)

    if existing:

        print(
            "\n⚠️ You already have an entry for today."
        )

        choice = input(
            "Replace today's entry? (y/n): "
        ).strip().lower()

        if choice != "y":

            print("No changes made.")

            return False

        data["entries"].remove(existing)

    new_entry = {
        "date": today,
        "items": items,
        "hours": hours,
        "category": category,
        "updated_at": datetime.now().isoformat(
            timespec="seconds"
        )
    }

    data["entries"].append(new_entry)

    data["entries"].sort(
        key=lambda entry: entry.get("date", "")
    )

    save_data(data)

    rebuild_text_file(data)

    print("\n✅ Today's progress saved.")

    return True


def view_today():

    data = load_data()

    today = date.today().isoformat()

    entry = get_entry(data, today)

    print("\n========================================")
    print("          TODAY'S PROGRESS")
    print("========================================")

    if not entry:

        print("No entry for today.")

        return

    print(f"Date:     {entry['date']}")
    print(
        f"Category: {entry.get('category', 'Other')}"
    )
    print(
        f"Hours:    {entry.get('hours', 0)}"
    )

    print("\nWork:")

    for item in entry.get("items", []):

        print(f"  • {item}")


def view_recent():

    data = load_data()

    entries = data["entries"][-7:]

    print("\n========================================")
    print("          RECENT PROGRESS")
    print("========================================")

    if not entries:

        print("No entries yet.")

        return

    for entry in reversed(entries):

        print(
            f"\n{entry['date']} | "
            f"{entry.get('category', 'Other')} | "
            f"{entry.get('hours', 0)}h"
        )

        for item in entry.get("items", []):

            print(f"  • {item}")


def calculate_streak(entries):

    days = set()

    for entry in entries:

        try:

            days.add(
                date.fromisoformat(
                    entry["date"]
                )
            )

        except (KeyError, ValueError):

            pass

    if not days:

        return 0

    current = date.today()

    if current not in days:

        current -= timedelta(days=1)

    streak = 0

    while current in days:

        streak += 1

        current -= timedelta(days=1)

    return streak


def show_statistics():

    data = load_data()

    entries = data["entries"]

    print("\n========================================")
    print("             STATISTICS")
    print("========================================")

    if not entries:

        print("No statistics yet.")

        return

    total_hours = sum(
        float(entry.get("hours", 0))
        for entry in entries
    )

    categories = {}

    for entry in entries:

        category = entry.get(
            "category",
            "Other"
        )

        hours = float(
            entry.get("hours", 0)
        )

        categories[category] = (
            categories.get(category, 0)
            + hours
        )

    streak = calculate_streak(entries)

    print(
        f"\n🔥 Current streak: {streak} days"
    )

    print(
        f"📅 Active days:    {len(entries)}"
    )

    print(
        f"⏱️ Total hours:    {total_hours:.1f}"
    )

    print("\nHours by category:")

    for category, hours in sorted(
        categories.items(),
        key=lambda item: item[1],
        reverse=True
    ):

        print(
            f"  {category:<15} "
            f"{hours:>6.1f}h"
        )


def weekly_summary():

    data = load_data()

    entries = data["entries"]

    end = date.today()

    start = end - timedelta(days=6)

    week_entries = []

    for entry in entries:

        try:

            entry_date = date.fromisoformat(
                entry["date"]
            )

            if start <= entry_date <= end:

                week_entries.append(entry)

        except (KeyError, ValueError):

            pass

    print("\n========================================")
    print("           WEEKLY SUMMARY")
    print("========================================")

    print(
        f"{start.isoformat()} → "
        f"{end.isoformat()}"
    )

    if not week_entries:

        print("\nNo activity this week.")

        return

    total_hours = sum(
        float(entry.get("hours", 0))
        for entry in week_entries
    )

    categories = {}

    for entry in week_entries:

        category = entry.get(
            "category",
            "Other"
        )

        hours = float(
            entry.get("hours", 0)
        )

        categories[category] = (
            categories.get(category, 0)
            + hours
        )

    print(
        f"\nDays worked: "
        f"{len(week_entries)}/7"
    )

    print(
        f"Total hours: "
        f"{total_hours:.1f}\n"
    )

    for category, hours in sorted(
        categories.items(),
        key=lambda item: item[1],
        reverse=True
    ):

        blocks = "█" * max(
            1,
            round(hours * 2)
        )

        print(
            f"{category:<15} "
            f"{blocks} "
            f"{hours:.1f}h"
        )


def git_sync():

    if not Path(".git").exists():

        print(
            "\n❌ This folder is not a Git repository."
        )

        return

    print("\n📦 Adding changes...")

    if run_command([
        "git",
        "add",
        "daily-progress.txt",
        "daily-progress.json"
    ]) is None:

        return

    status = run_command(
        ["git", "status", "--porcelain"]
    )

    if status is None:

        return

    if not status:

        print(
            "\nℹ️ Nothing new to commit."
        )

        return

    today = date.today().isoformat()

    commit_message = (
        f"docs: update daily progress {today}"
    )

    print("\n📝 Creating commit...")

    if run_command([
        "git",
        "commit",
        "-m",
        commit_message
    ]) is None:

        return

    print("\n🚀 Pushing to GitHub...")

    if run_command(["git", "push"]) is None:

        print(
            "\n❌ Push failed."
        )

        print(
            "The commit is saved locally."
        )

    else:

        print(
            "\n🎉 Successfully pushed to GitHub!"
        )


def main():

    while True:

        print("\n")
        print(
            "╔══════════════════════════════════════╗"
        )
        print(
            "║        DEV DAILY TRACKER            ║"
        )
        print(
            "╠══════════════════════════════════════╣"
        )
        print(
            "║ 1. Add/update today's progress     ║"
        )
        print(
            "║ 2. View today's progress           ║"
        )
        print(
            "║ 3. View recent progress            ║"
        )
        print(
            "║ 4. View statistics                 ║"
        )
        print(
            "║ 5. View weekly summary             ║"
        )
        print(
            "║ 6. Push changes to GitHub          ║"
        )
        print(
            "║ 7. Add progress and push           ║"
        )
        print(
            "║ 8. Exit                            ║"
        )
        print(
            "╚══════════════════════════════════════╝"
        )

        choice = input(
            "\nChoose an option: "
        ).strip()

        if choice == "1":

            add_or_update_entry()

        elif choice == "2":

            view_today()

        elif choice == "3":

            view_recent()

        elif choice == "4":

            show_statistics()

        elif choice == "5":

            weekly_summary()

        elif choice == "6":

            git_sync()

        elif choice == "7":

            if add_or_update_entry():

                git_sync()

        elif choice == "8":

            print("\nGoodbye 👋")

            break

        else:

            print(
                "\n⚠️ Invalid option."
            )

        input(
            "\nPress Enter to continue..."
        )


if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        print("\n\nExited.")

        sys.exit(0)